global:
  active_market: futures
  timeframe: 1d
  risk_per_trade_pct: 1.0
  default_bot_active: true
futures:
  default_leverage: 2
  margin_type: ISOLATED
  symbols:
  - BTC_USDT
spot:
  symbols:
  - BTC_USDT
trading:
  fee_rate: 0.001
  slippage: 0.0005
